// Code generated by entc, DO NOT EDIT.

package color

import (
	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/vmkevv/suprat-api/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Color {
	return predicate.Color(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Color {
	return predicate.Color(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Color {
	return predicate.Color(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Color {
	return predicate.Color(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Color {
	return predicate.Color(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Color {
	return predicate.Color(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Color {
	return predicate.Color(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Color {
	return predicate.Color(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Color {
	return predicate.Color(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Color {
	return predicate.Color(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldName), v))
	})
}

// Rgb applies equality check predicate on the "rgb" field. It's identical to RgbEQ.
func Rgb(v string) predicate.Color {
	return predicate.Color(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldRgb), v))
	})
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Color {
	return predicate.Color(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldName), v))
	})
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Color {
	return predicate.Color(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldName), v))
	})
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Color {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Color(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldName), v...))
	})
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Color {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Color(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldName), v...))
	})
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Color {
	return predicate.Color(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldName), v))
	})
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Color {
	return predicate.Color(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldName), v))
	})
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Color {
	return predicate.Color(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldName), v))
	})
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Color {
	return predicate.Color(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldName), v))
	})
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Color {
	return predicate.Color(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldName), v))
	})
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Color {
	return predicate.Color(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldName), v))
	})
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Color {
	return predicate.Color(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldName), v))
	})
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Color {
	return predicate.Color(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldName), v))
	})
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Color {
	return predicate.Color(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldName), v))
	})
}

// RgbEQ applies the EQ predicate on the "rgb" field.
func RgbEQ(v string) predicate.Color {
	return predicate.Color(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldRgb), v))
	})
}

// RgbNEQ applies the NEQ predicate on the "rgb" field.
func RgbNEQ(v string) predicate.Color {
	return predicate.Color(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldRgb), v))
	})
}

// RgbIn applies the In predicate on the "rgb" field.
func RgbIn(vs ...string) predicate.Color {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Color(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldRgb), v...))
	})
}

// RgbNotIn applies the NotIn predicate on the "rgb" field.
func RgbNotIn(vs ...string) predicate.Color {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Color(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldRgb), v...))
	})
}

// RgbGT applies the GT predicate on the "rgb" field.
func RgbGT(v string) predicate.Color {
	return predicate.Color(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldRgb), v))
	})
}

// RgbGTE applies the GTE predicate on the "rgb" field.
func RgbGTE(v string) predicate.Color {
	return predicate.Color(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldRgb), v))
	})
}

// RgbLT applies the LT predicate on the "rgb" field.
func RgbLT(v string) predicate.Color {
	return predicate.Color(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldRgb), v))
	})
}

// RgbLTE applies the LTE predicate on the "rgb" field.
func RgbLTE(v string) predicate.Color {
	return predicate.Color(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldRgb), v))
	})
}

// RgbContains applies the Contains predicate on the "rgb" field.
func RgbContains(v string) predicate.Color {
	return predicate.Color(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldRgb), v))
	})
}

// RgbHasPrefix applies the HasPrefix predicate on the "rgb" field.
func RgbHasPrefix(v string) predicate.Color {
	return predicate.Color(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldRgb), v))
	})
}

// RgbHasSuffix applies the HasSuffix predicate on the "rgb" field.
func RgbHasSuffix(v string) predicate.Color {
	return predicate.Color(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldRgb), v))
	})
}

// RgbEqualFold applies the EqualFold predicate on the "rgb" field.
func RgbEqualFold(v string) predicate.Color {
	return predicate.Color(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldRgb), v))
	})
}

// RgbContainsFold applies the ContainsFold predicate on the "rgb" field.
func RgbContainsFold(v string) predicate.Color {
	return predicate.Color(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldRgb), v))
	})
}

// HasActivities applies the HasEdge predicate on the "activities" edge.
func HasActivities() predicate.Color {
	return predicate.Color(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ActivitiesTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ActivitiesTable, ActivitiesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasActivitiesWith applies the HasEdge predicate on the "activities" edge with a given conditions (other predicates).
func HasActivitiesWith(preds ...predicate.Activity) predicate.Color {
	return predicate.Color(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ActivitiesInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ActivitiesTable, ActivitiesColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMeasurements applies the HasEdge predicate on the "measurements" edge.
func HasMeasurements() predicate.Color {
	return predicate.Color(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(MeasurementsTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MeasurementsTable, MeasurementsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMeasurementsWith applies the HasEdge predicate on the "measurements" edge with a given conditions (other predicates).
func HasMeasurementsWith(preds ...predicate.Measurement) predicate.Color {
	return predicate.Color(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(MeasurementsInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MeasurementsTable, MeasurementsColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Color) predicate.Color {
	return predicate.Color(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Color) predicate.Color {
	return predicate.Color(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Color) predicate.Color {
	return predicate.Color(func(s *sql.Selector) {
		p(s.Not())
	})
}
