// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// Activity is the predicate function for activity builders.
type Activity func(*sql.Selector)

// Color is the predicate function for color builders.
type Color func(*sql.Selector)

// Icon is the predicate function for icon builders.
type Icon func(*sql.Selector)

// Measure is the predicate function for measure builders.
type Measure func(*sql.Selector)

// Measurement is the predicate function for measurement builders.
type Measurement func(*sql.Selector)

// Record is the predicate function for record builders.
type Record func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
